[template]
src = "docker-compose.yml.tmpl"
dest = "/tmp/my-docker-compose.yml"
keys = [
"DATAGERRIT_IMAGE",
"datagerrit_name",
"datajenkins_image",
"datajenkins_name",
"pggerrit_name",
"pggerrit_name",
"pggerrit_postgres_user",
"pggerrit_postgres_password",
"pggerrit_postgres_db",
"gerrit_image",
"gerrit_name",
"gerrit_weburl",
"gerrit_httpd_listenurl",
"gerrit_database_type",
"gerrit_auth_type",
"gerrit_ldap_server",
"gerrit_ldap_accountbase",
"jenkins_image",
"jenkins_name",
"jenkins_opts",
"pgredmine_image",
"pgredmine_name",
"pgredmine_postgres_user",
"pgredmine_postgres_password",
"pgredmine_postgres_db",
"redmine_image",
"redmine_name",
"redmine_db_name",
"redmine_db_user",
"redmine_db_pass",
"redmine_redmin_relative_url_root",
"redmine_redmin_fetch_commits",
"nginxproxy_image",
"nginxproxy_name",
"nginxproxy_volumes",
]
